name: Overleaf Sync with Git
on:
  schedule:
    - cron: "* */6 * * *"
  push:
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Fetch the latest version from overleaf server
      run: |
        PROJECT_ID=${{ secrets.OVERLEAF_PROJECT_ID }}
        ZIP_OUTPUT_PATH="/tmp/main.zip"
        EXTRACTED_FILES_PATH="./artifacts/"
        COOKIE=$(echo ${{ secrets.OVERLEAF_COOKIE }} | sed 's/.*=//g')
        HOST=${{ secrets.OVERLEAF_HOST }}

        echo "Dumping zip file at $ZIP_OUTPUT_PATH"

        curl "https://$HOST/project/$PROJECT_ID/download/zip" \
          -H "authority: $HOST" \
          -H 'pragma: no-cache' \
          -H 'cache-control: no-cache' \
          -H 'upgrade-insecure-requests: 1' \
          -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
          -H 'accept-language: en-US,en;q=0.9' \
          -H "Cookie: sharelatex.sid=$COOKIE" \
          --output "$ZIP_OUTPUT_PATH" --create-dirs

        echo "Extracting all files at $EXTRACTED_FILES_PATH"

        unzip -o "$ZIP_OUTPUT_PATH" -d "$EXTRACTED_FILES_PATH"

    - name: Upload to Project Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: project
        path: ./artifacts/

    - uses: actions/checkout@v2
      with:
        path: repo/
    
    - run: |
        cd repo/
        mv .github ../
        rm -rf *
        mv ../.github ./
        cp -r ../artifacts/* ./
        git config user.name "Overleaf Sync Bot"
        git config user.email "actions@github.com"
        git add .
        if [[ $(git diff HEAD --stat) == '' ]]; then (echo 'Working tree is clean') 
        else (git commit -m "Sync with overleaf remote"  && git push) fi
